// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Directory struct {
	DirID     int64     `json:"dir_id"`
	Name      string    `json:"name"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
